In [1]:
ls

MapNamesToLogs.ipynb  Untitled.ipynb        bball-ref.js          fantasy.2015/         finalNames.py         includes/             node_modules/
README.md*            bball-ref-ad.js       cleanGameLogs.py      finalGameLog.py       gameLogs.ipynb        mapNames.py           players/

In [4]:
import pandas as pd
import numpy as np

game = 'fantasy.2015/Game.2015.csv'
game = pd.read_csv(game)

player = 'fantasy.2015/Player.2015.csv'
player = pd.read_csv(player)

playerGame = 'fantasy.2015/PlayerGame.2015.csv'
playerGame = pd.read_csv(playerGame)

playerGameP = 'fantasy.2015/PlayerGameProjection.2015.csv'
playerGameP = pd.read_csv(playerGameP)

playerSeason = 'fantasy.2015/PlayerSeason.2015.csv'
playerSeason = pd.read_csv(playerSeason)

team = 'fantasy.2015/Team.2015.csv'
team = pd.read_csv(team)

teamGame = 'fantasy.2015/TeamGame.2015.csv'
teamGame = pd.read_csv(teamGame)

teamSeason = 'fantasy.2015/TeamSeason.2015.csv'
teamSeason = pd.read_csv(teamSeason)

In [5]:
player

,PlayerID,SportsDataID,Status,TeamID,Team,Jersey,PositionCategory,Position,FirstName,LastName,...,Weight,BirthDate,BirthCity,BirthState,BirthCountry,HighSchool,College,Salary,PhotoUrl,Experience
0,20000438,NaN,Active,28,LAC,34,F,SF,Paul,Pierce,...,235,10/13/1977,Oakland,California,NaN,NaN,Kansas,3376000,http://static.fantasydata.com/headshots/nba/lo...,17
1,20000439,NaN,Active,1,WAS,42,F,PF,Nene,Hilario,...,250,9/13/1982,Sao Carlos,Brazil,NaN,NaN,&nbsp;,13000000,http://static.fantasydata.com/headshots/nba/lo...,13
2,20000440,NaN,Active,1,WAS,13,C,C,Marcin,Gortat,...,240,2/17/1984,Lodz,Poland,NaN,NaN,&nbsp;,11217391,http://static.fantasydata.com/headshots/nba/lo...,8
3,20000441,NaN,Active,1,WAS,3,G,SG,Bradley,Beal,...,207,6/28/1993,St. Louis,Missouri,NaN,NaN,Florida,5694674,http://static.fantasydata.com/headshots/nba/lo...,3
4,20000442,NaN,Active,1,WAS,2,G,PG,John,Wall,...,195,9/6/1990,Raleigh,North Carolina,NaN,NaN,Kentucky,15851950,http://static.fantasydata.com/headshots/nba/lo...,5
5,20000443,NaN,Active,1,WAS,22,F,SF,Otto,Porter,...,198,6/3/1993,St. Louis,Missouri,NaN,NaN,Georgetown,4662960,http://static.fantasydata.com/headshots/nba/lo...,2
6,20000444,NaN,Active,1,WAS,90,F,PF,Drew,Gooden,...,250,9/24/1981,Oakland,California,NaN,NaN,Kansas,3300000,http://static.fantasydata.com/headshots/nba/lo...,13
7,20000445,NaN,Active,1,WAS,7,G,PG,Ramon,Sessions,...,190,4/11/1986,Myrtle Beach,South Carolina,NaN,NaN,Nevada,2170465,http://static.fantasydata.com/headshots/nba/lo...,8
8,20000446,NaN,Active,6,NY,1,F,PF,Kevin,Seraphin,...,278,12/7/1989,Cayenne,France,NaN,NaN,&nbsp;,2814000,http://static.fantasydata.com/headshots/nba/lo...,5
9,20000447,NaN,Active,24,SA,18,F,SF,Rasual,Butler,...,215,5/23/1979,Philadelphia,Pennsylvania,NaN,NaN,La Salle,947276,http://static.fantasydata.com/headshots/nba/lo...,13
10,20000448,NaN,Inactive,NaN,NaN,1,G,PG,Will,Bynum,...,185,1/4/1983,Chicago,Illinois,NaN,NaN,NaN,NaN,http://static.fantasydata.com/headshots/nba/lo...,NaN
11,20000449,NaN,Active,1,WAS,43,F,PF,Kris,Humphries,...,235,2/6/1985,Minneapolis,Minnesota,NaN,NaN,Minnesota,4440000,http://static.fantasydata.com/headshots/nba/lo...,11
12,20000450,NaN,Active,1,WAS,9,F,SF,Martell,Webster,...,230,12/4/1986,Edmonds,Washington,NaN,NaN,&nbsp;,5613500,http://static.fantasydata.com/headshots/nba/lo...,10
13,20000451,NaN,Active,1,WAS,45,C,C,DeJuan,Blair,...,270,4/22/1989,Pittsburgh,Pennsylvania,NaN,NaN,Pittsburgh,2000000,http://static.fantasydata.com/headshots/nba/lo...,6
14,20000452,NaN,Active,1,WAS,17,G,SG,Garrett,Temple,...,195,5/8/1986,Baton Rouge,Louisiana,NaN,NaN,LSU,1100602,http://static.fantasydata.com/headshots/nba/lo...,6
15,20000453,NaN,Active,10,TOR,31,F,SF,Terrence,Ross,...,195,2/5/1991,Portland,Oregon,Oregon,NaN,Washington,3553917,http://static.fantasydata.com/headshots/nba/lo...,3
16,20000454,NaN,Active,2,CHA,50,F,PF,Tyler,Hansbrough,...,250,11/3/1985,Columbia,Missouri,NaN,NaN,North Carolina,947276,http://static.fantasydata.com/headshots/nba/lo...,6
17,20000455,NaN,Active,10,TOR,17,C,C,Jonas,Valanciunas,...,255,5/6/1992,Utena,Lithuania,NaN,NaN,&nbsp;,4660482,http://static.fantasydata.com/headshots/nba/lo...,3
18,20000456,NaN,Active,10,TOR,10,G,SG,DeMar,DeRozan,...,220,8/7/1989,Compton,California,NaN,NaN,USC,10050000,http://static.fantasydata.com/headshots/nba/lo...,6
19,20000457,NaN,Active,10,TOR,7,G,PG,Kyle,Lowry,...,205,3/25/1986,Philadelphia,Pennsylvania,NaN,NaN,Villanova,12000000,http://static.fantasydata.com/headshots/nba/lo...,9