In [109]:
ls

MapNamesToLogs.ipynb  bball-ref.js          finalGameLog.py       gameLogs.ipynb        mapNames.py           players/
README.md*            cleanGameLogs.py      finalNames.py         includes/             node_modules/

In [119]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 500)

n = 'players/2015/names/allnames.csv'
names = pd.read_csv(n)

g = 'players/2015/logs/alllogs.csv'
games = pd.read_csv(g)

In [121]:
games

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,pname
0,1,1,2014-10-29,24-023,NYK,NaN,CHI,L (-24),0,21:28,3,6,0.500,0,0,NaN,0,0,NaN,2,4,6,1,0,1,2,4,6,3.4,-15,acyqu01
1,2,2,2014-10-30,24-024,NYK,@,CLE,W (+5),1,22:27,4,7,0.571,0,0,NaN,0,0,NaN,6,4,10,2,0,1,2,6,8,7.8,2,acyqu01
2,3,3,2014-11-02,24-027,NYK,NaN,CHO,W (+3),1,20:20,1,4,0.250,0,1,0,0,0,NaN,0,3,3,2,0,0,0,2,2,1.1,11,acyqu01
3,5,4,2014-11-05,24-030,NYK,@,DET,L (-3),0,13:42,0,1,0.000,0,0,NaN,0,0,NaN,2,4,6,1,0,1,2,1,0,0.9,-6,acyqu01
4,6,5,2014-11-07,24-032,NYK,@,BRK,L (-11),0,22:14,3,7,0.429,0,0,NaN,1,2,0.500,6,3,9,0,0,0,3,3,7,3.8,-15,acyqu01
5,7,6,2014-11-08,24-033,NYK,@,ATL,L (-7),0,13:34,1,1,1.000,0,0,NaN,0,0,NaN,1,2,3,0,0,0,1,2,2,1.2,-10,acyqu01
6,9,7,2014-11-12,24-037,NYK,NaN,ORL,L (-2),1,20:12,1,1,1.000,0,0,NaN,0,0,NaN,2,2,4,1,0,0,2,4,2,0.8,-8,acyqu01
7,10,8,2014-11-14,24-039,NYK,NaN,UTA,L (-2),0,19:39,2,2,1.000,0,0,NaN,2,2,1.000,1,1,2,0,0,0,0,3,6,5.2,-5,acyqu01
8,11,9,2014-11-16,24-041,NYK,NaN,DEN,W (+16),1,31:10,3,7,0.429,0,1,0,2,2,1.000,1,7,8,3,3,0,0,3,8,11.0,-3,acyqu01
9,13,10,2014-11-19,24-044,NYK,@,MIN,L (-16),1,32:18,4,8,0.500,0,0,NaN,1,1,1.000,2,6,8,0,0,0,3,2,9,4.4,-4,acyqu01
10,14,11,2014-11-22,24-047,NYK,NaN,PHI,W (+8),1,23:57,3,6,0.500,0,0,NaN,4,4,1.000,0,5,5,2,0,0,0,4,10,8.3,14,acyqu01
11,15,12,2014-11-24,24-049,NYK,@,HOU,L (-5),1,25:21,0,4,0.000,0,0,NaN,1,2,0.500,4,4,8,3,0,0,1,1,1,2.5,-6,acyqu01
12,16,13,2014-11-26,24-051,NYK,@,DAL,L (-7),1,36:08,3,8,0.375,0,0,NaN,2,4,0.500,0,6,6,1,0,0,1,3,8,3.1,-1,acyqu01
13,17,14,2014-11-28,24-053,NYK,@,OKC,L (-27),1,22:53,1,3,0.333,0,0,NaN,3,4,0.750,1,5,6,0,0,0,1,2,5,3.3,-17,acyqu01
14,18,15,2014-11-30,24-055,NYK,NaN,MIA,L (-7),1,23:53,1,1,1.000,0,0,NaN,1,1,1.000,1,2,3,1,0,0,1,1,3,3.3,-1,acyqu01
15,19,16,2014-12-02,24-057,NYK,NaN,BRK,L (-5),0,10:28,2,3,0.667,0,0,NaN,0,0,NaN,0,2,2,0,1,0,2,4,4,0.7,-9,acyqu01
16,20,17,2014-12-04,24-059,NYK,NaN,CLE,L (-3),1,31:12,6,8,0.750,0,0,NaN,3,4,0.750,2,4,6,3,0,1,3,1,15,13.4,-15,acyqu01
17,21,18,2014-12-05,24-060,NYK,@,CHO,L (-1),0,12:04,2,4,0.500,1,1,1,0,0,NaN,0,4,4,0,0,0,0,2,5,3.4,-6,acyqu01
18,22,19,2014-12-07,24-062,NYK,NaN,POR,L (-4),1,18:33,2,2,1.000,0,0,NaN,2,2,1.000,0,4,4,1,0,0,0,2,6,6.5,0,acyqu01
19,23,20,2014-12-09,24-064,NYK,@,NOP,L (-11),1,17:55,2,3,0.667,0,0,NaN,0,0,NaN,0,1,1,1,1,0,0,1,4,4.3,-2,acyqu01
20,24,21,2014-12-10,24-065,NYK,@,SAS,L (-14),1,24:59,3,6,0.500,0,0,NaN,2,2,1.000,0,5,5,1,0,0,0,3,8,6.0,4,acyqu01
21,25,22,2014-12-12,24-067,NYK,@,BOS,W (+6),1,17:17,0,1,0.000,0,0,NaN,0,0,NaN,1,3,4,3,2,0,1,1,0,3.6,16,acyqu01
22,26,23,2014-12-14,24-069,NYK,NaN,TOR,L (-5),1,30:50,1,3,0.333,0,0,NaN,0,0,NaN,2,3,5,3,1,0,0,2,2,4.9,11,acyqu01
23,27,24,2014-12-16,24-071,NYK,NaN,DAL,L (-20),1,20:02,3,4,0.750,0,0,NaN,0,0,NaN,1,4,5,0,0,2,1,0,6,6.7,-14,acyqu01
24,28,25,2014-12-18,24-073,NYK,@,CHI,L (-6),0,9:53,2,4,0.500,0,0,NaN,2,2,1.000,1,3,4,0,0,0,0,1,6,5.2,1,acyqu01
25,29,26,2014-12-20,24-075,NYK,NaN,PHO,L (-9),1,16:54,0,0,NaN,0,0,NaN,0,0,NaN,3,1,4,1,0,0,3,3,0,-1.1,-9,acyqu01
26,30,27,2014-12-21,24-076,NYK,@,TOR,L (-10),1,25:39,3,8,0.375,0,0,NaN,1,2,0.500,1,3,4,1,0,2,2,3,7,2.7,-14,acyqu01
27,31,28,2014-12-25,24-080,NYK,NaN,WAS,L (-11),0,11:53,2,3,0.667,0,0,NaN,0,0,NaN,0,2,2,1,0,0,0,2,4,3.2,-1,acyqu01
28,33,29,2014-12-28,24-083,NYK,@,POR,L (-22),0,23:51,5,9,0.556,2,2,1,0,0,NaN,1,3,4,1,0,0,3,1,12,6.6,-4,acyqu01
29,34,30,2014-12-31,24-086,NYK,@,LAC,L (-21),0,18:38,3,5,0.600,0,1,0,2,2,1.000,0,3,3,0,0,0,0,2,8,5.8,-7,acyqu01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13436,73,58,2015-03-27,26-011,LAC,@,PHI,W (+21),1,29:09,5,8,0.625,0,0,NaN,0,0,NaN,1,4,5,8,0,0,1,3,10,11.7,13,griffbl01
13437,74,59,2015-03-29,26-013,LAC,@,BOS,W (+13),1,32:50,7,14,0.500,0,0,NaN,7,9,0.778,3,6,9,5,1,1,0,2,21,21.5,14,griffbl01
13438,75,60,2015-03-31,26-015,LAC,NaN,GSW,L (-4),1,42:31,16,25,0.640,0,0,NaN,8,8,1.000,2,10,12,5,1,3,3,4,40,35.3,7,griffbl01
13439,76,61,2015-04-01,26-016,LAC,@,POR,W (+4),1,38:23,10,18,0.556,2,2,1,2,2,1.000,1,6,7,8,1,1,4,3,24,20.0,4,griffbl01
13440,77,62,2015-04-04,26-019,LAC,@,DEN,W (+15),1,25:24,6,12,0.500,0,0,NaN,0,5,0.000,2,2,4,7,1,0,3,5,12,6.9,17,griffbl01
13441,78,63,2015-04-05,26-020,LAC,@,LAL,W (+28),1,30:40,8,14,0.571,0,0,NaN,2,2,1.000,1,4,5,5,0,0,0,1,18,16.4,28,griffbl01
13442,79,64,2015-04-07,26-022,LAC,NaN,LAL,W (+5),1,36:07,11,20,0.550,0,0,NaN,5,8,0.625,1,6,7,6,0,1,3,2,27,19.8,15,griffbl01
13443,80,65,2015-04-11,26-026,LAC,NaN,MEM,W (+8),1,38:14,6,21,0.286,0,1,0,6,6,1.000,3,5,8,6,2,1,5,3,18,10.0,14,griffbl01
13444,81,66,2015-04-13,26-028,LAC,NaN,DEN,W (+7),1,40:04,7,18,0.389,0,0,NaN,8,9,0.889,2,7,9,8,0,2,2,2,22,19.5,16,griffbl01
13445,82,67,2015-04-14,26-029,LAC,@,PHO,W (+11),1,29:27,8,14,0.571,0,0,NaN,4,4,1.000,0,8,8,5,2,0,1,2,20,19.5,21,griffbl01
13446,3,1,2014-11-03,25-311,BRK,NaN,OKC,W (+31),0,4:41,2,3,0.667,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,2,4,1.9,-2,gutiejo01
13447,7,2,2014-11-12,25-320,BRK,@,PHO,L (-8),0,0:06,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,0,0,0.0,0,gutiejo01
13448,8,3,2014-11-13,25-321,BRK,@,GSW,L (-8),0,0:10,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,0,0,0.0,0,gutiejo01
13449,9,4,2014-11-15,25-323,BRK,@,POR,L (-10),0,2:56,0,2,0.000,0,0,NaN,0,0,NaN,0,0,0,0,0,0,1,1,0,-2.8,-9,gutiejo01
13450,13,5,2014-11-22,25-330,BRK,@,SAS,L (-12),0,2:30,0,0,NaN,0,0,NaN,0,0,NaN,0,2,2,1,0,0,0,0,0,1.3,3,gutiejo01
13451,15,6,2014-11-30,25-338,BRK,NaN,CHI,L (-18),0,3:57,2,3,0.667,0,0,NaN,2,2,1.000,0,0,0,0,0,0,0,0,6,4.7,3,gutiejo01
13452,16,7,2014-12-02,25-340,BRK,@,NYK,W (+5),0,2:51,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,2,0,-0.8,-2,gutiejo01
13453,18,8,2014-12-05,25-343,BRK,NaN,ATL,L (-23),0,15:35,3,6,0.500,0,1,0,0,1,0.000,0,2,2,3,1,0,0,3,6,5.1,-3,gutiejo01
13454,19,9,2014-12-08,25-346,BRK,NaN,CLE,L (-22),0,6:05,0,0,NaN,0,0,NaN,0,0,NaN,0,2,2,1,0,0,1,1,0,-0.1,4,gutiejo01
13455,20,10,2014-12-10,25-348,BRK,@,CHI,L (-25),0,4:44,0,0,NaN,0,0,NaN,0,0,NaN,0,1,1,2,0,0,1,0,0,0.7,-4,gutiejo01
13456,21,11,2015-01-29,26-033,MIL,@,ORL,W (+15),0,6:13,1,2,0.500,0,0,NaN,1,2,0.500,0,0,0,1,1,0,0,0,3,3.3,-3,gutiejo01
13457,22,12,2015-01-31,26-035,MIL,NaN,POR,W (+7),0,9:23,1,1,1.000,0,0,NaN,0,0,NaN,0,4,4,0,0,0,1,2,2,1.1,-7,gutiejo01
13458,23,13,2015-02-02,26-037,MIL,@,TOR,W (+7),1,27:45,0,5,0.000,0,2,0,0,0,NaN,2,2,4,5,1,0,3,3,0,-1.2,3,gutiejo01
13459,25,14,2015-02-06,26-041,MIL,@,HOU,L (-6),0,15:56,5,5,1.000,0,0,NaN,3,3,1.000,1,1,2,0,1,0,0,3,13,12.3,6,gutiejo01
13460,26,15,2015-02-07,26-042,MIL,NaN,BOS,W (+3),0,10:15,0,1,0.000,0,0,NaN,0,0,NaN,1,1,2,2,0,0,0,1,0,1.3,2,gutiejo01
13461,27,16,2015-02-09,26-044,MIL,NaN,BRK,W (+6),0,9:16,1,2,0.500,0,0,NaN,0,0,NaN,0,1,1,0,0,0,1,0,2,0.3,7,gutiejo01
13462,28,17,2015-02-11,26-046,MIL,NaN,SAC,W (+8),0,15:23,2,3,0.667,0,0,NaN,1,1,1.000,0,2,2,3,1,0,1,2,5,5.6,2,gutiejo01
13463,31,18,2015-04-12,26-106,MIL,NaN,BRK,W (+23),0,4:09,1,1,1.000,0,0,NaN,0,0,NaN,0,0,0,1,1,0,0,1,2,3.0,-4,gutiejo01
13464,32,19,2015-04-13,26-107,MIL,@,PHI,W (+10),0,13:00,1,1,1.000,0,0,NaN,0,0,NaN,0,0,0,1,0,0,2,2,2,-0.4,-13,gutiejo01
13465,33,20,2015-04-15,26-109,MIL,NaN,BOS,L (-5),0,19:29,3,6,0.500,0,0,NaN,2,4,0.500,1,2,3,2,0,0,1,2,8,5.1,-10,gutiejo01

In [112]:
#gamesNames = pd.concat([gamesd, namesd])

In [113]:
#gamesNames

In [114]:
#gamesd = gamesd.append(namesd)

In [115]:
#gamesNames = pd.concat([gamesd, namesd], axis=1)

In [116]:
#gamesd

In [124]:
result = pd.concat([games, names], axis=1, join_axes=[games.index])

In [125]:
result

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,pname,Player,From,To,Pos,Ht,Wt,Birth Date,College,pname
0,1,1,2014-10-29,24-023,NYK,NaN,CHI,L (-24),0,21:28,3,6,0.500,0,0,NaN,0,0,NaN,2,4,6,1,0,1,2,4,6,3.4,-15,acyqu01,Quincy Acy,2013,2016,F,6-7,240,October 6 1990,Baylor University,acyqu01
1,2,2,2014-10-30,24-024,NYK,@,CLE,W (+5),1,22:27,4,7,0.571,0,0,NaN,0,0,NaN,6,4,10,2,0,1,2,6,8,7.8,2,acyqu01,Alexis Ajinca,2009,2016,C,7-2,248,May 6 1988,NaN,ajincal01
2,3,3,2014-11-02,24-027,NYK,NaN,CHO,W (+3),1,20:20,1,4,0.250,0,1,0,0,0,NaN,0,3,3,2,0,0,0,2,2,1.1,11,acyqu01,Cole Aldrich,2011,2016,C,6-11,250,October 31 1988,University of Kansas,aldrico01
3,5,4,2014-11-05,24-030,NYK,@,DET,L (-3),0,13:42,0,1,0.000,0,0,NaN,0,0,NaN,2,4,6,1,0,1,2,1,0,0.9,-6,acyqu01,Lavoy Allen,2012,2016,F-C,6-9,255,February 4 1989,Temple University,allenla01
4,6,5,2014-11-07,24-032,NYK,@,BRK,L (-11),0,22:14,3,7,0.429,0,0,NaN,1,2,0.500,6,3,9,0,0,0,3,3,7,3.8,-15,acyqu01,Lou Amundson,2007,2015,F,6-9,220,December 7 1982,University of Nevada Las Vegas,amundlo01
5,7,6,2014-11-08,24-033,NYK,@,ATL,L (-7),0,13:34,1,1,1.000,0,0,NaN,0,0,NaN,1,2,3,0,0,0,1,2,2,1.2,-10,acyqu01,Chris Andersen,2002,2016,F-C,6-10,245,July 7 1978,Blinn College,anderch01
6,9,7,2014-11-12,24-037,NYK,NaN,ORL,L (-2),1,20:12,1,1,1.000,0,0,NaN,0,0,NaN,2,2,4,1,0,0,2,4,2,0.8,-8,acyqu01,Alan Anderson,2006,2015,G-F,6-6,220,October 16 1982,Michigan State University,anderal01
7,10,8,2014-11-14,24-039,NYK,NaN,UTA,L (-2),0,19:39,2,2,1.000,0,0,NaN,2,2,1.000,1,1,2,0,0,0,0,3,6,5.2,-5,acyqu01,Kyle Anderson,2015,2016,G-F,6-9,230,September 20 1993,University of California Los Angeles,anderky01
8,11,9,2014-11-16,24-041,NYK,NaN,DEN,W (+16),1,31:10,3,7,0.429,0,1,0,2,2,1.000,1,7,8,3,3,0,0,3,8,11.0,-3,acyqu01,Ryan Anderson,2009,2016,F,6-10,240,May 6 1988,University of California,anderry01
9,13,10,2014-11-19,24-044,NYK,@,MIN,L (-16),1,32:18,4,8,0.500,0,0,NaN,1,1,1.000,2,6,8,0,0,0,3,2,9,4.4,-4,acyqu01,Giannis Antetokounmpo,2014,2016,F-G,6-11,222,December 6 1994,NaN,antetgi01
10,14,11,2014-11-22,24-047,NYK,NaN,PHI,W (+8),1,23:57,3,6,0.500,0,0,NaN,4,4,1.000,0,5,5,2,0,0,0,4,10,8.3,14,acyqu01,Carmelo Anthony,2004,2016,F,6-8,240,May 29 1984,Syracuse University,anthoca01
11,15,12,2014-11-24,24-049,NYK,@,HOU,L (-5),1,25:21,0,4,0.000,0,0,NaN,1,2,0.500,4,4,8,3,0,0,1,1,1,2.5,-6,acyqu01,Joel Anthony,2008,2015,C,6-9,245,August 9 1982,University of Nevada Las Vegas,anthojo01
12,16,13,2014-11-26,24-051,NYK,@,DAL,L (-7),1,36:08,3,8,0.375,0,0,NaN,2,4,0.500,0,6,6,1,0,0,1,3,8,3.1,-1,acyqu01,Pero Antic,2014,2015,F,6-11,260,July 29 1982,NaN,anticpe01
13,17,14,2014-11-28,24-053,NYK,@,OKC,L (-27),1,22:53,1,3,0.333,0,0,NaN,3,4,0.750,1,5,6,0,0,0,1,2,5,3.3,-17,acyqu01,Trevor Ariza,2005,2016,F,6-8,215,June 30 1985,University of California Los Angeles,arizatr01
14,18,15,2014-11-30,24-055,NYK,NaN,MIA,L (-7),1,23:53,1,1,1.000,0,0,NaN,1,1,1.000,1,2,3,1,0,0,1,1,3,3.3,-1,acyqu01,Darrell Arthur,2009,2016,F,6-9,235,March 25 1988,University of Kansas,arthuda01
15,19,16,2014-12-02,24-057,NYK,NaN,BRK,L (-5),0,10:28,2,3,0.667,0,0,NaN,0,0,NaN,0,2,2,0,1,0,2,4,4,0.7,-9,acyqu01,Omer Asik,2011,2016,C,7-0,255,July 4 1986,NaN,asikom01
16,20,17,2014-12-04,24-059,NYK,NaN,CLE,L (-3),1,31:12,6,8,0.750,0,0,NaN,3,4,0.750,2,4,6,3,0,1,3,1,15,13.4,-15,acyqu01,Luke Babbitt,2011,2016,F,6-9,225,June 20 1989,University of Nevada Reno,babbilu01
17,21,18,2014-12-05,24-060,NYK,@,CHO,L (-1),0,12:04,2,4,0.500,1,1,1,0,0,NaN,0,4,4,0,0,0,0,2,5,3.4,-6,acyqu01,Cameron Bairstow,2015,2016,F-C,6-9,250,December 7 1990,University of New Mexico,bairsca01
18,22,19,2014-12-07,24-062,NYK,NaN,POR,L (-4),1,18:33,2,2,1.000,0,0,NaN,2,2,1.000,0,4,4,1,0,0,0,2,6,6.5,0,acyqu01,Leandro Barbosa,2004,2016,G,6-3,194,November 28 1982,NaN,barbole01
19,23,20,2014-12-09,24-064,NYK,@,NOP,L (-11),1,17:55,2,3,0.667,0,0,NaN,0,0,NaN,0,1,1,1,1,0,0,1,4,4.3,-2,acyqu01,Andrea Bargnani,2007,2016,F-C,7-0,245,October 26 1985,NaN,bargnan01
20,24,21,2014-12-10,24-065,NYK,@,SAS,L (-14),1,24:59,3,6,0.500,0,0,NaN,2,2,1.000,0,5,5,1,0,0,0,3,8,6.0,4,acyqu01,Harrison Barnes,2013,2016,F,6-8,210,May 30 1992,University of North Carolina,barneha02
21,25,22,2014-12-12,24-067,NYK,@,BOS,W (+6),1,17:17,0,1,0.000,0,0,NaN,0,0,NaN,1,3,4,3,2,0,1,1,0,3.6,16,acyqu01,Matt Barnes,2004,2016,F,6-7,226,March 9 1980,University of California Los Angeles,barnema02
22,26,23,2014-12-14,24-069,NYK,NaN,TOR,L (-5),1,30:50,1,3,0.333,0,0,NaN,0,0,NaN,2,3,5,3,1,0,0,2,2,4.9,11,acyqu01,Earl Barron,2006,2015,C,7-0,250,August 14 1981,University of Memphis,barroea01
23,27,24,2014-12-16,24-071,NYK,NaN,DAL,L (-20),1,20:02,3,4,0.750,0,0,NaN,0,0,NaN,1,4,5,0,0,2,1,0,6,6.7,-14,acyqu01,Will Barton,2013,2016,G,6-6,175,January 6 1991,University of Memphis,bartowi01
24,28,25,2014-12-18,24-073,NYK,@,CHI,L (-6),0,9:53,2,4,0.500,0,0,NaN,2,2,1.000,1,3,4,0,0,0,0,1,6,5.2,1,acyqu01,Brandon Bass,2006,2016,F,6-8,250,April 30 1985,Louisiana State University,bassbr01
25,29,26,2014-12-20,24-075,NYK,NaN,PHO,L (-9),1,16:54,0,0,NaN,0,0,NaN,0,0,NaN,3,1,4,1,0,0,3,3,0,-1.1,-9,acyqu01,Nicolas Batum,2009,2016,F-G,6-8,200,December 14 1988,NaN,batumni01
26,30,27,2014-12-21,24-076,NYK,@,TOR,L (-10),1,25:39,3,8,0.375,0,0,NaN,1,2,0.500,1,3,4,1,0,2,2,3,7,2.7,-14,acyqu01,Jerryd Bayless,2009,2016,G,6-3,200,August 20 1988,University of Arizona,bayleje01
27,31,28,2014-12-25,24-080,NYK,NaN,WAS,L (-11),0,11:53,2,3,0.667,0,0,NaN,0,0,NaN,0,2,2,1,0,0,0,2,4,3.2,-1,acyqu01,Aron Baynes,2013,2016,F-C,6-10,260,December 9 1986,Washington State University,baynear01
28,33,29,2014-12-28,24-083,NYK,@,POR,L (-22),0,23:51,5,9,0.556,2,2,1,0,0,NaN,1,3,4,1,0,0,3,1,12,6.6,-4,acyqu01,Kent Bazemore,2013,2016,G-F,6-5,201,July 1 1989,Old Dominion University,bazemke01
29,34,30,2014-12-31,24-086,NYK,@,LAC,L (-21),0,18:38,3,5,0.600,0,1,0,2,2,1.000,0,3,3,0,0,0,0,2,8,5.8,-7,acyqu01,Bradley Beal,2013,2016,G,6-5,207,June 28 1993,University of Florida,bealbr01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13436,73,58,2015-03-27,26-011,LAC,@,PHI,W (+21),1,29:09,5,8,0.625,0,0,NaN,0,0,NaN,1,4,5,8,0,0,1,3,10,11.7,13,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13437,74,59,2015-03-29,26-013,LAC,@,BOS,W (+13),1,32:50,7,14,0.500,0,0,NaN,7,9,0.778,3,6,9,5,1,1,0,2,21,21.5,14,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13438,75,60,2015-03-31,26-015,LAC,NaN,GSW,L (-4),1,42:31,16,25,0.640,0,0,NaN,8,8,1.000,2,10,12,5,1,3,3,4,40,35.3,7,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13439,76,61,2015-04-01,26-016,LAC,@,POR,W (+4),1,38:23,10,18,0.556,2,2,1,2,2,1.000,1,6,7,8,1,1,4,3,24,20.0,4,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13440,77,62,2015-04-04,26-019,LAC,@,DEN,W (+15),1,25:24,6,12,0.500,0,0,NaN,0,5,0.000,2,2,4,7,1,0,3,5,12,6.9,17,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13441,78,63,2015-04-05,26-020,LAC,@,LAL,W (+28),1,30:40,8,14,0.571,0,0,NaN,2,2,1.000,1,4,5,5,0,0,0,1,18,16.4,28,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13442,79,64,2015-04-07,26-022,LAC,NaN,LAL,W (+5),1,36:07,11,20,0.550,0,0,NaN,5,8,0.625,1,6,7,6,0,1,3,2,27,19.8,15,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13443,80,65,2015-04-11,26-026,LAC,NaN,MEM,W (+8),1,38:14,6,21,0.286,0,1,0,6,6,1.000,3,5,8,6,2,1,5,3,18,10.0,14,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13444,81,66,2015-04-13,26-028,LAC,NaN,DEN,W (+7),1,40:04,7,18,0.389,0,0,NaN,8,9,0.889,2,7,9,8,0,2,2,2,22,19.5,16,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13445,82,67,2015-04-14,26-029,LAC,@,PHO,W (+11),1,29:27,8,14,0.571,0,0,NaN,4,4,1.000,0,8,8,5,2,0,1,2,20,19.5,21,griffbl01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13446,3,1,2014-11-03,25-311,BRK,NaN,OKC,W (+31),0,4:41,2,3,0.667,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,2,4,1.9,-2,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13447,7,2,2014-11-12,25-320,BRK,@,PHO,L (-8),0,0:06,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,0,0,0.0,0,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13448,8,3,2014-11-13,25-321,BRK,@,GSW,L (-8),0,0:10,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,0,0,0.0,0,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13449,9,4,2014-11-15,25-323,BRK,@,POR,L (-10),0,2:56,0,2,0.000,0,0,NaN,0,0,NaN,0,0,0,0,0,0,1,1,0,-2.8,-9,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13450,13,5,2014-11-22,25-330,BRK,@,SAS,L (-12),0,2:30,0,0,NaN,0,0,NaN,0,0,NaN,0,2,2,1,0,0,0,0,0,1.3,3,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13451,15,6,2014-11-30,25-338,BRK,NaN,CHI,L (-18),0,3:57,2,3,0.667,0,0,NaN,2,2,1.000,0,0,0,0,0,0,0,0,6,4.7,3,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13452,16,7,2014-12-02,25-340,BRK,@,NYK,W (+5),0,2:51,0,0,NaN,0,0,NaN,0,0,NaN,0,0,0,0,0,0,0,2,0,-0.8,-2,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13453,18,8,2014-12-05,25-343,BRK,NaN,ATL,L (-23),0,15:35,3,6,0.500,0,1,0,0,1,0.000,0,2,2,3,1,0,0,3,6,5.1,-3,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13454,19,9,2014-12-08,25-346,BRK,NaN,CLE,L (-22),0,6:05,0,0,NaN,0,0,NaN,0,0,NaN,0,2,2,1,0,0,1,1,0,-0.1,4,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13455,20,10,2014-12-10,25-348,BRK,@,CHI,L (-25),0,4:44,0,0,NaN,0,0,NaN,0,0,NaN,0,1,1,2,0,0,1,0,0,0.7,-4,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13456,21,11,2015-01-29,26-033,MIL,@,ORL,W (+15),0,6:13,1,2,0.500,0,0,NaN,1,2,0.500,0,0,0,1,1,0,0,0,3,3.3,-3,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13457,22,12,2015-01-31,26-035,MIL,NaN,POR,W (+7),0,9:23,1,1,1.000,0,0,NaN,0,0,NaN,0,4,4,0,0,0,1,2,2,1.1,-7,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13458,23,13,2015-02-02,26-037,MIL,@,TOR,W (+7),1,27:45,0,5,0.000,0,2,0,0,0,NaN,2,2,4,5,1,0,3,3,0,-1.2,3,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13459,25,14,2015-02-06,26-041,MIL,@,HOU,L (-6),0,15:56,5,5,1.000,0,0,NaN,3,3,1.000,1,1,2,0,1,0,0,3,13,12.3,6,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13460,26,15,2015-02-07,26-042,MIL,NaN,BOS,W (+3),0,10:15,0,1,0.000,0,0,NaN,0,0,NaN,1,1,2,2,0,0,0,1,0,1.3,2,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13461,27,16,2015-02-09,26-044,MIL,NaN,BRK,W (+6),0,9:16,1,2,0.500,0,0,NaN,0,0,NaN,0,1,1,0,0,0,1,0,2,0.3,7,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13462,28,17,2015-02-11,26-046,MIL,NaN,SAC,W (+8),0,15:23,2,3,0.667,0,0,NaN,1,1,1.000,0,2,2,3,1,0,1,2,5,5.6,2,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13463,31,18,2015-04-12,26-106,MIL,NaN,BRK,W (+23),0,4:09,1,1,1.000,0,0,NaN,0,0,NaN,0,0,0,1,1,0,0,1,2,3.0,-4,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13464,32,19,2015-04-13,26-107,MIL,@,PHI,W (+10),0,13:00,1,1,1.000,0,0,NaN,0,0,NaN,0,0,0,1,0,0,2,2,2,-0.4,-13,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13465,33,20,2015-04-15,26-109,MIL,NaN,BOS,L (-5),0,19:29,3,6,0.500,0,0,NaN,2,4,0.500,1,2,3,2,0,0,1,2,8,5.1,-10,gutiejo01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN