In [3]:
ls

MapNamesToLogs.ipynb  cleanGameLogs.py      gameLogs.ipynb        mapNames.py           players/
bball-ref.js          finalGameLog.py       includes/             node_modules/

In [18]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 500)

logs = 'players/2015/gamelogsd.csv'
names = 'players/2015/namesd.csv'

gamesd = pd.read_csv(logs)
namesd = pd.read_csv(names)

In [19]:
gamesd

,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,pname
0,1,1,2014-10-29,33-172,NYK,NaN,CHI,L (-24),1,19:51,2,5,0.400,0,0,NaN,2,2,1.000,2,2,4,2,0,3,1,2,6,7.0,-3,dalemsa01
1,2,2,2014-10-30,33-173,NYK,@,CLE,W (+5),1,5:34,0,1,0.000,0,0,NaN,0,0,NaN,0,2,2,0,0,0,0,0,0,-0.1,-2,dalemsa01
2,3,3,2014-11-02,33-176,NYK,NaN,CHO,W (+3),1,22:21,0,2,0.000,0,0,NaN,0,0,NaN,3,5,8,1,0,0,3,4,0,-1.7,11,dalemsa01
3,4,4,2014-11-04,33-178,NYK,NaN,WAS,L (-15),1,20:12,1,5,0.200,0,0,NaN,0,0,NaN,3,5,8,3,0,2,2,2,2,3.2,-12,dalemsa01
4,5,5,2014-11-05,33-179,NYK,@,DET,L (-3),1,14:30,1,3,0.333,0,0,NaN,0,0,NaN,0,2,2,3,1,2,0,2,2,4.6,-8,dalemsa01
5,6,6,2014-11-07,33-181,NYK,@,BRK,L (-11),1,4:52,1,3,0.333,0,0,NaN,0,0,NaN,0,1,1,0,0,0,1,2,2,-1.2,0,dalemsa01
6,7,7,2014-11-08,33-182,NYK,@,ATL,L (-7),1,24:46,3,4,0.750,0,0,NaN,1,1,1.000,2,4,6,2,0,3,1,2,7,9.7,-1,dalemsa01
7,8,8,2014-11-10,33-184,NYK,NaN,ATL,L (-6),1,16:05,0,0,NaN,0,0,NaN,0,0,NaN,2,5,7,0,0,0,3,1,0,-0.5,3,dalemsa01
8,9,9,2014-11-12,33-186,NYK,NaN,ORL,L (-2),1,27:24,1,3,0.333,0,0,NaN,0,0,NaN,2,5,7,4,0,5,0,0,2,9.5,1,dalemsa01
9,10,10,2014-11-14,33-188,NYK,NaN,UTA,L (-2),1,18:19,2,5,0.400,0,0,NaN,0,0,NaN,0,4,4,2,0,0,0,1,4,3.5,-10,dalemsa01
10,11,11,2014-11-16,33-190,NYK,NaN,DEN,W (+16),1,22:08,4,8,0.500,0,0,NaN,0,0,NaN,4,4,8,2,1,1,0,2,8,10.3,16,dalemsa01
11,12,12,2014-11-18,33-192,NYK,@,MIL,L (-4),1,17:25,1,2,0.500,0,0,NaN,0,0,NaN,1,1,2,1,0,2,2,2,2,1.3,-20,dalemsa01
12,13,13,2014-11-19,33-193,NYK,@,MIN,L (-16),1,8:22,1,1,1.000,0,0,NaN,1,2,0.500,0,1,1,0,0,1,1,1,3,1.9,-13,dalemsa01
13,14,14,2014-11-22,33-196,NYK,NaN,PHI,W (+8),1,23:33,3,6,0.500,0,0,NaN,0,0,NaN,3,4,7,0,0,1,2,4,6,3.4,11,dalemsa01
14,15,15,2014-11-24,33-198,NYK,@,HOU,L (-5),1,15:19,3,3,1.000,0,0,NaN,0,0,NaN,0,1,1,1,1,1,2,2,6,5.0,1,dalemsa01
15,16,16,2014-11-26,33-200,NYK,@,DAL,L (-7),1,25:28,5,10,0.500,0,0,NaN,3,4,0.750,3,10,13,0,2,2,2,5,13,12.1,-4,dalemsa01
16,17,17,2014-11-28,33-202,NYK,@,OKC,L (-27),1,19:07,4,10,0.400,0,0,NaN,1,1,1.000,1,6,7,1,0,2,0,1,9,7.8,-8,dalemsa01
17,18,18,2014-11-30,33-204,NYK,NaN,MIA,L (-7),1,19:33,1,6,0.167,0,0,NaN,0,0,NaN,4,6,10,0,1,1,0,3,2,3.3,-10,dalemsa01
18,19,19,2014-12-02,33-206,NYK,NaN,BRK,L (-5),1,14:53,1,2,0.500,0,0,NaN,0,0,NaN,1,2,3,1,0,1,2,3,2,0.5,-11,dalemsa01
19,20,20,2014-12-04,33-208,NYK,NaN,CLE,L (-3),0,18:01,3,6,0.500,0,0,NaN,0,0,NaN,2,7,9,0,2,0,2,5,6,4.5,-11,dalemsa01
20,21,21,2014-12-05,33-209,NYK,@,CHO,L (-1),1,21:09,3,6,0.500,0,0,NaN,0,0,NaN,2,6,8,1,0,2,3,0,6,5.3,-13,dalemsa01
21,22,22,2014-12-07,33-211,NYK,NaN,POR,L (-4),0,17:17,2,4,0.500,0,0,NaN,0,0,NaN,0,4,4,2,0,2,2,4,4,2.4,-5,dalemsa01
22,23,23,2014-12-09,33-213,NYK,@,NOP,L (-11),0,7:35,1,3,0.333,0,0,NaN,0,0,NaN,0,3,3,0,0,1,1,2,2,0.1,-4,dalemsa01
23,24,24,2014-12-10,33-214,NYK,@,SAS,L (-14),0,14:34,1,4,0.250,0,0,NaN,0,0,NaN,2,4,6,0,1,1,2,1,2,1.5,-17,dalemsa01
24,25,25,2014-12-12,33-216,NYK,@,BOS,W (+6),0,22:09,2,3,0.667,0,0,NaN,2,2,1.000,1,4,5,1,2,1,0,2,6,9.2,-11,dalemsa01
25,26,26,2014-12-14,33-218,NYK,NaN,TOR,L (-5),0,13:12,0,1,0.000,0,0,NaN,2,2,1.000,0,3,3,1,0,2,1,2,2,2.5,-10,dalemsa01
26,27,27,2014-12-16,33-220,NYK,NaN,DAL,L (-20),0,5:53,0,0,NaN,0,0,NaN,0,0,NaN,1,1,2,0,0,0,1,0,0,0.0,-6,dalemsa01
27,28,28,2014-12-18,33-222,NYK,@,CHI,L (-6),0,12:57,2,4,0.500,0,0,NaN,0,0,NaN,3,2,5,1,0,0,0,3,4,4.2,-10,dalemsa01
28,29,29,2014-12-20,33-224,NYK,NaN,PHO,L (-9),0,26:36,2,7,0.286,0,0,NaN,1,2,0.500,7,5,12,0,2,1,2,4,5,6.0,0,dalemsa01
29,30,30,2014-12-21,33-225,NYK,@,TOR,L (-10),0,13:39,1,1,1.000,0,0,NaN,0,0,NaN,1,1,2,0,1,0,1,1,2,2.3,-7,dalemsa01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,52,25,2015-02-09,26-133,OKC,@,DEN,W (+10),1,36:35,13,19,0.684,7,12,0.583,7,11,0.636,0,4,4,2,1,0,4,2,40,29.1,18,duranke01
1600,53,26,2015-02-11,26-135,OKC,NaN,MEM,W (+16),1,34:03,9,15,0.600,4,6,0.667,4,4,1.000,0,10,10,3,1,3,0,0,26,27.3,28,duranke01
1601,54,27,2015-02-19,26-143,OKC,NaN,DAL,W (+15),1,37:14,4,14,0.286,2,6,0.333,2,2,1.000,1,5,6,5,1,0,2,1,12,8.1,15,duranke01
1602,18,1,2014-12-02,26-064,OKC,@,NOP,L (-8),1,29:34,9,18,0.500,3,8,0.375,6,7,0.857,0,3,3,2,0,0,5,2,27,14.1,-8,duranke01
1603,19,2,2014-12-05,26-067,OKC,@,PHI,W (+12),1,29:08,3,11,0.273,1,2,0.500,3,4,0.750,0,6,6,3,0,1,2,1,10,5.3,7,duranke01
1604,20,3,2014-12-07,26-069,OKC,@,DET,W (+2),1,29:28,10,19,0.526,1,4,0.250,7,8,0.875,0,4,4,4,1,0,2,2,28,20.5,7,duranke01
1605,21,4,2014-12-09,26-071,OKC,NaN,MIL,W (+13),1,28:56,7,11,0.636,1,5,0.200,8,8,1.000,0,9,9,7,1,1,4,0,23,23.4,16,duranke01
1606,22,5,2014-12-11,26-073,OKC,NaN,CLE,W (+9),1,30:07,6,14,0.429,1,4,0.250,6,6,1.000,0,6,6,5,2,2,3,0,19,17.3,6,duranke01
1607,23,6,2014-12-12,26-074,OKC,@,MIN,W (+19),1,28:22,5,8,0.625,1,2,0.500,5,5,1.000,1,3,4,5,0,2,6,3,16,11.7,6,duranke01
1608,24,7,2014-12-14,26-076,OKC,NaN,PHO,W (+24),1,24:20,8,13,0.615,1,2,0.500,6,6,1.000,0,8,8,2,2,1,4,2,23,18.8,21,duranke01
1609,25,8,2014-12-16,26-078,OKC,@,SAC,W (+12),1,35:17,12,25,0.480,1,4,0.250,1,3,0.333,0,3,3,2,1,0,2,1,26,13.4,15,duranke01
1610,26,9,2014-12-18,26-080,OKC,@,GSW,L (-5),1,18:44,10,13,0.769,5,6,0.833,5,7,0.714,0,2,2,2,0,1,2,1,30,24.4,5,duranke01
1611,33,10,2014-12-31,26-093,OKC,NaN,PHO,W (+3),1,39:41,13,23,0.565,6,11,0.545,12,12,1.000,0,10,10,7,0,1,5,3,44,35.5,12,duranke01
1612,34,11,2015-01-02,26-095,OKC,NaN,WAS,W (+7),1,31:19,12,18,0.667,4,7,0.571,6,7,0.857,0,8,8,2,0,1,2,3,34,27.1,5,duranke01
1613,35,12,2015-01-05,26-098,OKC,@,GSW,L (-26),1,31:50,3,16,0.188,1,4,0.250,7,11,0.636,0,10,10,3,2,0,2,2,14,6.7,-13,duranke01
1614,36,13,2015-01-07,26-100,OKC,@,SAC,L (-21),1,32:34,8,20,0.400,3,7,0.429,5,7,0.714,1,8,9,0,1,1,4,3,24,12.0,-17,duranke01
1615,37,14,2015-01-09,26-102,OKC,NaN,UTA,W (+5),1,36:05,14,21,0.667,2,7,0.286,2,2,1.000,1,4,5,6,1,1,2,2,32,27.9,23,duranke01
1616,38,15,2015-01-15,26-108,OKC,@,HOU,L (-11),1,40:11,8,12,0.667,4,6,0.667,4,4,1.000,3,7,10,1,0,3,4,1,24,21.4,-11,duranke01
1617,39,16,2015-01-16,26-109,OKC,NaN,GSW,W (+12),1,38:39,14,18,0.778,3,5,0.600,5,5,1.000,0,9,9,4,1,0,2,0,36,33.5,15,duranke01
1618,40,17,2015-01-18,26-111,OKC,@,ORL,W (+28),1,27:32,7,10,0.700,0,1,0.000,7,7,1.000,3,8,11,8,1,1,3,1,21,25.2,25,duranke01
1619,41,18,2015-01-20,26-113,OKC,@,MIA,W (+8),1,39:17,9,24,0.375,0,8,0.000,1,1,1.000,1,7,8,8,4,1,0,1,19,18.5,14,duranke01
1620,42,19,2015-01-21,26-114,OKC,@,WAS,W (+2),1,44:30,10,23,0.435,4,10,0.400,10,11,0.909,0,7,7,3,0,1,3,1,34,23.0,4,duranke01
1621,43,20,2015-01-23,26-116,OKC,@,ATL,L (-10),1,40:38,8,22,0.364,3,9,0.333,2,4,0.500,0,3,3,3,1,1,2,0,21,10.7,-15,duranke01
1622,44,21,2015-01-25,26-118,OKC,@,CLE,L (-10),1,39:56,12,23,0.522,1,5,0.200,7,9,0.778,1,5,6,9,0,2,1,3,32,27.6,-12,duranke01
1623,47,22,2015-01-31,26-124,OKC,@,MEM,L (-11),1,36:51,5,16,0.313,0,5,0.000,5,6,0.833,0,7,7,4,1,0,4,0,15,7.3,-14,duranke01
1624,50,23,2015-02-06,26-130,OKC,NaN,NOP,L (-3),1,42:46,9,26,0.346,3,10,0.300,6,7,0.857,2,3,5,4,2,1,2,2,27,17.0,0,duranke01
1625,51,24,2015-02-08,26-132,OKC,NaN,LAC,W (+23),1,29:00,10,15,0.667,2,3,0.667,7,7,1.000,2,3,5,6,0,0,2,3,29,25.8,16,duranke01
1626,52,25,2015-02-09,26-133,OKC,@,DEN,W (+10),1,36:35,13,19,0.684,7,12,0.583,7,11,0.636,0,4,4,2,1,0,4,2,40,29.1,18,duranke01
1627,53,26,2015-02-11,26-135,OKC,NaN,MEM,W (+16),1,34:03,9,15,0.600,4,6,0.667,4,4,1.000,0,10,10,3,1,3,0,0,26,27.3,28,duranke01
1628,54,27,2015-02-19,26-143,OKC,NaN,DAL,W (+15),1,37:14,4,14,0.286,2,6,0.333,2,2,1.000,1,5,6,5,1,0,2,1,12,8.1,15,duranke01

In [20]:
namesd

,Player,From,To,Pos,Ht,Wt,Birth Date,College,pname
0,Anthony Davis,2013,2016,F-C,6-10,253,March 11 1993,University of Kentucky,davisan02
1,Ed Davis,2011,2016,F,6-10,240,June 5 1989,University of North Carolina,davised01
2,Glen Davis,2008,2015,F,6-9,289,January 1 1986,Louisiana State University,davisgl01
3,Austin Daye,2010,2015,F,6-11,220,June 5 1988,Gonzaga University,dayeau01
4,Luol Deng,2005,2016,F,6-9,220,April 16 1985,Duke University,denglu01
5,Boris Diaw,2004,2016,F-C,6-8,250,April 16 1982,NaN,diawbo01
6,Gorgui Dieng,2014,2016,C,6-11,241,January 18 1990,University of Louisville,dienggo01
7,Larry Drew,2015,2015,G,6-2,180,March 5 1990,University of California Los Angeles,drewla02

In [21]:
#gamesNames = pd.concat([gamesd, namesd])

In [22]:
#gamesNames

In [23]:
#gamesd = gamesd.append(namesd)

In [ ]:
gamesd = pd.concat([gamesd, namesd], axis=1)

In [24]:
gamesd

,+/-,3P,3P%,3PA,AST,Age,BLK,Birth Date,College,DRB,Date,FG,FG%,FGA,FT,FT%,FTA,From,G,GS,GmSc,Ht,MP,ORB,Opp,PF,PTS,Player,Pos,Rk,STL,TOV,TRB,Tm,To,Unnamed: 5,Unnamed: 7,Wt,pname
0,-3,0,NaN,0,2,33-172,3,NaN,NaN,2,2014-10-29,2,0.400,5,2,1.000,2,NaN,1,1,7.0,NaN,19:51,2,CHI,2,6,NaN,NaN,1,0,1,4,NYK,NaN,NaN,L (-24),NaN,dalemsa01
1,-2,0,NaN,0,0,33-173,0,NaN,NaN,2,2014-10-30,0,0.000,1,0,NaN,0,NaN,2,1,-0.1,NaN,5:34,0,CLE,0,0,NaN,NaN,2,0,0,2,NYK,NaN,@,W (+5),NaN,dalemsa01
2,11,0,NaN,0,1,33-176,0,NaN,NaN,5,2014-11-02,0,0.000,2,0,NaN,0,NaN,3,1,-1.7,NaN,22:21,3,CHO,4,0,NaN,NaN,3,0,3,8,NYK,NaN,NaN,W (+3),NaN,dalemsa01
3,-12,0,NaN,0,3,33-178,2,NaN,NaN,5,2014-11-04,1,0.200,5,0,NaN,0,NaN,4,1,3.2,NaN,20:12,3,WAS,2,2,NaN,NaN,4,0,2,8,NYK,NaN,NaN,L (-15),NaN,dalemsa01
4,-8,0,NaN,0,3,33-179,2,NaN,NaN,2,2014-11-05,1,0.333,3,0,NaN,0,NaN,5,1,4.6,NaN,14:30,0,DET,2,2,NaN,NaN,5,1,0,2,NYK,NaN,@,L (-3),NaN,dalemsa01
5,0,0,NaN,0,0,33-181,0,NaN,NaN,1,2014-11-07,1,0.333,3,0,NaN,0,NaN,6,1,-1.2,NaN,4:52,0,BRK,2,2,NaN,NaN,6,0,1,1,NYK,NaN,@,L (-11),NaN,dalemsa01
6,-1,0,NaN,0,2,33-182,3,NaN,NaN,4,2014-11-08,3,0.750,4,1,1.000,1,NaN,7,1,9.7,NaN,24:46,2,ATL,2,7,NaN,NaN,7,0,1,6,NYK,NaN,@,L (-7),NaN,dalemsa01
7,3,0,NaN,0,0,33-184,0,NaN,NaN,5,2014-11-10,0,NaN,0,0,NaN,0,NaN,8,1,-0.5,NaN,16:05,2,ATL,1,0,NaN,NaN,8,0,3,7,NYK,NaN,NaN,L (-6),NaN,dalemsa01
8,1,0,NaN,0,4,33-186,5,NaN,NaN,5,2014-11-12,1,0.333,3,0,NaN,0,NaN,9,1,9.5,NaN,27:24,2,ORL,0,2,NaN,NaN,9,0,0,7,NYK,NaN,NaN,L (-2),NaN,dalemsa01
9,-10,0,NaN,0,2,33-188,0,NaN,NaN,4,2014-11-14,2,0.400,5,0,NaN,0,NaN,10,1,3.5,NaN,18:19,0,UTA,1,4,NaN,NaN,10,0,0,4,NYK,NaN,NaN,L (-2),NaN,dalemsa01
10,16,0,NaN,0,2,33-190,1,NaN,NaN,4,2014-11-16,4,0.500,8,0,NaN,0,NaN,11,1,10.3,NaN,22:08,4,DEN,2,8,NaN,NaN,11,1,0,8,NYK,NaN,NaN,W (+16),NaN,dalemsa01
11,-20,0,NaN,0,1,33-192,2,NaN,NaN,1,2014-11-18,1,0.500,2,0,NaN,0,NaN,12,1,1.3,NaN,17:25,1,MIL,2,2,NaN,NaN,12,0,2,2,NYK,NaN,@,L (-4),NaN,dalemsa01
12,-13,0,NaN,0,0,33-193,1,NaN,NaN,1,2014-11-19,1,1.000,1,1,0.500,2,NaN,13,1,1.9,NaN,8:22,0,MIN,1,3,NaN,NaN,13,0,1,1,NYK,NaN,@,L (-16),NaN,dalemsa01
13,11,0,NaN,0,0,33-196,1,NaN,NaN,4,2014-11-22,3,0.500,6,0,NaN,0,NaN,14,1,3.4,NaN,23:33,3,PHI,4,6,NaN,NaN,14,0,2,7,NYK,NaN,NaN,W (+8),NaN,dalemsa01
14,1,0,NaN,0,1,33-198,1,NaN,NaN,1,2014-11-24,3,1.000,3,0,NaN,0,NaN,15,1,5.0,NaN,15:19,0,HOU,2,6,NaN,NaN,15,1,2,1,NYK,NaN,@,L (-5),NaN,dalemsa01
15,-4,0,NaN,0,0,33-200,2,NaN,NaN,10,2014-11-26,5,0.500,10,3,0.750,4,NaN,16,1,12.1,NaN,25:28,3,DAL,5,13,NaN,NaN,16,2,2,13,NYK,NaN,@,L (-7),NaN,dalemsa01
16,-8,0,NaN,0,1,33-202,2,NaN,NaN,6,2014-11-28,4,0.400,10,1,1.000,1,NaN,17,1,7.8,NaN,19:07,1,OKC,1,9,NaN,NaN,17,0,0,7,NYK,NaN,@,L (-27),NaN,dalemsa01
17,-10,0,NaN,0,0,33-204,1,NaN,NaN,6,2014-11-30,1,0.167,6,0,NaN,0,NaN,18,1,3.3,NaN,19:33,4,MIA,3,2,NaN,NaN,18,1,0,10,NYK,NaN,NaN,L (-7),NaN,dalemsa01
18,-11,0,NaN,0,1,33-206,1,NaN,NaN,2,2014-12-02,1,0.500,2,0,NaN,0,NaN,19,1,0.5,NaN,14:53,1,BRK,3,2,NaN,NaN,19,0,2,3,NYK,NaN,NaN,L (-5),NaN,dalemsa01
19,-11,0,NaN,0,0,33-208,0,NaN,NaN,7,2014-12-04,3,0.500,6,0,NaN,0,NaN,20,0,4.5,NaN,18:01,2,CLE,5,6,NaN,NaN,20,2,2,9,NYK,NaN,NaN,L (-3),NaN,dalemsa01
20,-13,0,NaN,0,1,33-209,2,NaN,NaN,6,2014-12-05,3,0.500,6,0,NaN,0,NaN,21,1,5.3,NaN,21:09,2,CHO,0,6,NaN,NaN,21,0,3,8,NYK,NaN,@,L (-1),NaN,dalemsa01
21,-5,0,NaN,0,2,33-211,2,NaN,NaN,4,2014-12-07,2,0.500,4,0,NaN,0,NaN,22,0,2.4,NaN,17:17,0,POR,4,4,NaN,NaN,22,0,2,4,NYK,NaN,NaN,L (-4),NaN,dalemsa01
22,-4,0,NaN,0,0,33-213,1,NaN,NaN,3,2014-12-09,1,0.333,3,0,NaN,0,NaN,23,0,0.1,NaN,7:35,0,NOP,2,2,NaN,NaN,23,0,1,3,NYK,NaN,@,L (-11),NaN,dalemsa01
23,-17,0,NaN,0,0,33-214,1,NaN,NaN,4,2014-12-10,1,0.250,4,0,NaN,0,NaN,24,0,1.5,NaN,14:34,2,SAS,1,2,NaN,NaN,24,1,2,6,NYK,NaN,@,L (-14),NaN,dalemsa01
24,-11,0,NaN,0,1,33-216,1,NaN,NaN,4,2014-12-12,2,0.667,3,2,1.000,2,NaN,25,0,9.2,NaN,22:09,1,BOS,2,6,NaN,NaN,25,2,0,5,NYK,NaN,@,W (+6),NaN,dalemsa01
25,-10,0,NaN,0,1,33-218,2,NaN,NaN,3,2014-12-14,0,0.000,1,2,1.000,2,NaN,26,0,2.5,NaN,13:12,0,TOR,2,2,NaN,NaN,26,0,1,3,NYK,NaN,NaN,L (-5),NaN,dalemsa01
26,-6,0,NaN,0,0,33-220,0,NaN,NaN,1,2014-12-16,0,NaN,0,0,NaN,0,NaN,27,0,0.0,NaN,5:53,1,DAL,0,0,NaN,NaN,27,0,1,2,NYK,NaN,NaN,L (-20),NaN,dalemsa01
27,-10,0,NaN,0,1,33-222,0,NaN,NaN,2,2014-12-18,2,0.500,4,0,NaN,0,NaN,28,0,4.2,NaN,12:57,3,CHI,3,4,NaN,NaN,28,0,0,5,NYK,NaN,@,L (-6),NaN,dalemsa01
28,0,0,NaN,0,0,33-224,1,NaN,NaN,5,2014-12-20,2,0.286,7,1,0.500,2,NaN,29,0,6.0,NaN,26:36,7,PHO,4,5,NaN,NaN,29,2,2,12,NYK,NaN,NaN,L (-9),NaN,dalemsa01
29,-7,0,NaN,0,0,33-225,0,NaN,NaN,1,2014-12-21,1,1.000,1,0,NaN,0,NaN,30,0,2.3,NaN,13:39,1,TOR,1,2,NaN,NaN,30,1,1,2,NYK,NaN,@,L (-10),NaN,dalemsa01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1607,6,1,0.500,2,5,26-074,2,NaN,NaN,3,2014-12-12,5,0.625,8,5,1.000,5,NaN,6,1,11.7,NaN,28:22,1,MIN,3,16,NaN,NaN,23,0,6,4,OKC,NaN,@,W (+19),NaN,duranke01
1608,21,1,0.500,2,2,26-076,1,NaN,NaN,8,2014-12-14,8,0.615,13,6,1.000,6,NaN,7,1,18.8,NaN,24:20,0,PHO,2,23,NaN,NaN,24,2,4,8,OKC,NaN,NaN,W (+24),NaN,duranke01
1609,15,1,0.250,4,2,26-078,0,NaN,NaN,3,2014-12-16,12,0.480,25,1,0.333,3,NaN,8,1,13.4,NaN,35:17,0,SAC,1,26,NaN,NaN,25,1,2,3,OKC,NaN,@,W (+12),NaN,duranke01
1610,5,5,0.833,6,2,26-080,1,NaN,NaN,2,2014-12-18,10,0.769,13,5,0.714,7,NaN,9,1,24.4,NaN,18:44,0,GSW,1,30,NaN,NaN,26,0,2,2,OKC,NaN,@,L (-5),NaN,duranke01
1611,12,6,0.545,11,7,26-093,1,NaN,NaN,10,2014-12-31,13,0.565,23,12,1.000,12,NaN,10,1,35.5,NaN,39:41,0,PHO,3,44,NaN,NaN,33,0,5,10,OKC,NaN,NaN,W (+3),NaN,duranke01
1612,5,4,0.571,7,2,26-095,1,NaN,NaN,8,2015-01-02,12,0.667,18,6,0.857,7,NaN,11,1,27.1,NaN,31:19,0,WAS,3,34,NaN,NaN,34,0,2,8,OKC,NaN,NaN,W (+7),NaN,duranke01
1613,-13,1,0.250,4,3,26-098,0,NaN,NaN,10,2015-01-05,3,0.188,16,7,0.636,11,NaN,12,1,6.7,NaN,31:50,0,GSW,2,14,NaN,NaN,35,2,2,10,OKC,NaN,@,L (-26),NaN,duranke01
1614,-17,3,0.429,7,0,26-100,1,NaN,NaN,8,2015-01-07,8,0.400,20,5,0.714,7,NaN,13,1,12.0,NaN,32:34,1,SAC,3,24,NaN,NaN,36,1,4,9,OKC,NaN,@,L (-21),NaN,duranke01
1615,23,2,0.286,7,6,26-102,1,NaN,NaN,4,2015-01-09,14,0.667,21,2,1.000,2,NaN,14,1,27.9,NaN,36:05,1,UTA,2,32,NaN,NaN,37,1,2,5,OKC,NaN,NaN,W (+5),NaN,duranke01
1616,-11,4,0.667,6,1,26-108,3,NaN,NaN,7,2015-01-15,8,0.667,12,4,1.000,4,NaN,15,1,21.4,NaN,40:11,3,HOU,1,24,NaN,NaN,38,0,4,10,OKC,NaN,@,L (-11),NaN,duranke01
1617,15,3,0.600,5,4,26-109,0,NaN,NaN,9,2015-01-16,14,0.778,18,5,1.000,5,NaN,16,1,33.5,NaN,38:39,0,GSW,0,36,NaN,NaN,39,1,2,9,OKC,NaN,NaN,W (+12),NaN,duranke01
1618,25,0,0.000,1,8,26-111,1,NaN,NaN,8,2015-01-18,7,0.700,10,7,1.000,7,NaN,17,1,25.2,NaN,27:32,3,ORL,1,21,NaN,NaN,40,1,3,11,OKC,NaN,@,W (+28),NaN,duranke01
1619,14,0,0.000,8,8,26-113,1,NaN,NaN,7,2015-01-20,9,0.375,24,1,1.000,1,NaN,18,1,18.5,NaN,39:17,1,MIA,1,19,NaN,NaN,41,4,0,8,OKC,NaN,@,W (+8),NaN,duranke01
1620,4,4,0.400,10,3,26-114,1,NaN,NaN,7,2015-01-21,10,0.435,23,10,0.909,11,NaN,19,1,23.0,NaN,44:30,0,WAS,1,34,NaN,NaN,42,0,3,7,OKC,NaN,@,W (+2),NaN,duranke01
1621,-15,3,0.333,9,3,26-116,1,NaN,NaN,3,2015-01-23,8,0.364,22,2,0.500,4,NaN,20,1,10.7,NaN,40:38,0,ATL,0,21,NaN,NaN,43,1,2,3,OKC,NaN,@,L (-10),NaN,duranke01
1622,-12,1,0.200,5,9,26-118,2,NaN,NaN,5,2015-01-25,12,0.522,23,7,0.778,9,NaN,21,1,27.6,NaN,39:56,1,CLE,3,32,NaN,NaN,44,0,1,6,OKC,NaN,@,L (-10),NaN,duranke01
1623,-14,0,0.000,5,4,26-124,0,NaN,NaN,7,2015-01-31,5,0.313,16,5,0.833,6,NaN,22,1,7.3,NaN,36:51,0,MEM,0,15,NaN,NaN,47,1,4,7,OKC,NaN,@,L (-11),NaN,duranke01
1624,0,3,0.300,10,4,26-130,1,NaN,NaN,3,2015-02-06,9,0.346,26,6,0.857,7,NaN,23,1,17.0,NaN,42:46,2,NOP,2,27,NaN,NaN,50,2,2,5,OKC,NaN,NaN,L (-3),NaN,duranke01
1625,16,2,0.667,3,6,26-132,0,NaN,NaN,3,2015-02-08,10,0.667,15,7,1.000,7,NaN,24,1,25.8,NaN,29:00,2,LAC,3,29,NaN,NaN,51,0,2,5,OKC,NaN,NaN,W (+23),NaN,duranke01
1626,18,7,0.583,12,2,26-133,0,NaN,NaN,4,2015-02-09,13,0.684,19,7,0.636,11,NaN,25,1,29.1,NaN,36:35,0,DEN,2,40,NaN,NaN,52,1,4,4,OKC,NaN,@,W (+10),NaN,duranke01
1627,28,4,0.667,6,3,26-135,3,NaN,NaN,10,2015-02-11,9,0.600,15,4,1.000,4,NaN,26,1,27.3,NaN,34:03,0,MEM,0,26,NaN,NaN,53,1,0,10,OKC,NaN,NaN,W (+16),NaN,duranke01
1628,15,2,0.333,6,5,26-143,0,NaN,NaN,5,2015-02-19,4,0.286,14,2,1.000,2,NaN,27,1,8.1,NaN,37:14,1,DAL,1,12,NaN,NaN,54,1,2,6,OKC,NaN,NaN,W (+15),NaN,duranke01
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March 11 1993,University of Kentucky,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013,NaN,NaN,NaN,6-10,NaN,NaN,NaN,NaN,NaN,Anthony Davis,F-C,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,253,davisan02
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,June 5 1989,University of North Carolina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011,NaN,NaN,NaN,6-10,NaN,NaN,NaN,NaN,NaN,Ed Davis,F,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,240,davised01
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,January 1 1986,Louisiana State University,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,NaN,6-9,NaN,NaN,NaN,NaN,NaN,Glen Davis,F,NaN,NaN,NaN,NaN,NaN,2015,NaN,NaN,289,davisgl01
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,June 5 1988,Gonzaga University,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,NaN,NaN,NaN,6-11,NaN,NaN,NaN,NaN,NaN,Austin Daye,F,NaN,NaN,NaN,NaN,NaN,2015,NaN,NaN,220,dayeau01
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,April 16 1985,Duke University,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005,NaN,NaN,NaN,6-9,NaN,NaN,NaN,NaN,NaN,Luol Deng,F,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,220,denglu01
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,April 16 1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,NaN,NaN,NaN,6-8,NaN,NaN,NaN,NaN,NaN,Boris Diaw,F-C,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,250,diawbo01
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,January 18 1990,University of Louisville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,NaN,NaN,NaN,6-11,NaN,NaN,NaN,NaN,NaN,Gorgui Dieng,C,NaN,NaN,NaN,NaN,NaN,2016,NaN,NaN,241,dienggo01
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March 5 1990,University of California Los Angeles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015,NaN,NaN,NaN,6-2,NaN,NaN,NaN,NaN,NaN,Larry Drew,G,NaN,NaN,NaN,NaN,NaN,2015,NaN,NaN,180,drewla02